### ISSUE TITLE
Update module on PuppetForge

### ISSUE THREAD

**Issue by dennislaumen** [thias/puppet-vsftpd#4]
Since Debian/Ubuntu support was added a couple of days ago it would be nice if the version on PuppetForge could be updated.

**Comment by thias** [comment]
Done : http://forge.puppetlabs.com/thias/vsftpd/0.1.4
(the changelog doesn't appear any more... I've filed a but against the forge for that)

**Comment by dennislaumen** [comment]
Great! Thanks for the extremely quick response! Not as important as my previous request but related: you might consider updating the tags on PuppetForge to reflect the additional OSes which are now supported.

Thanks again!

**Comment by thias** [comment]
Indeed! Done :-)

**Comment by dennislaumen** [comment]
Awesome! Thanks :-).
